title: MAIDEAS
description: Pages related to Python, NumPy and of course ... Machine Learning.
google_site_verification_key: 1yU377-5avAh8CpOrU11zN6SuYYP0mq6g_wA7BP5NtM
remote_theme: maideas/maideas-clean-theme
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-seo-tag
