theme: jekyll-theme-architect
title: Welcome to m-a-h-e's GitHub Pages.
description: Pages related to Python, NumPy and of course ... Machine Learning.
markdown: kramdown
toc-categories: [Neural Network Basics, NumPy Basics]
